### ISSUE TITLE
ee_dataset

### ISSUE THREAD

**Issue by SebMounLeakmited** [Skydipper/CNN-tests#1]
hi thanks for sharing i start using earth engine, i try run Sentinel2_classifier.ipynb. i have an error ee_dateset doesn t exist. it looks like to be a handmade library, doesn't it?

**Comment by benlaken** [comment]
Hi, thanks for the interest in this code - at the moment it is still under heavy development from within Vizzuality and requires access to our private repos and keys to run, so it is not intended for public use just yet.
